### ISSUE TITLE
Fix rpc error.

### ISSUE THREAD

**Issue by pjkaufman** [acstech/doppler-events#53]
There is an unexpected error when running all of the services together.

**Comment by pjkaufman** [comment]
error: `panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13a8590]

goroutine 4383 [running]:
github.com/acstech/doppler-events/vendor/github.com/couchbase/gocb.(*Bucket).startKvOpTrace(0x0, 0x1640144, 0x8, 0x7, 0xc4228e55f8)
	/Users/peterkaufman/go/src/github.com/acstech/doppler-events/vendor/github.com/couchbase/gocb/bucket.go:33 +0x60
github.com/acstech/doppler-events/vendor/github.com/couchbase/gocb.(*Bucket).lookupIn(0x0, 0x0, 0x0, 0xc421db35e0, 0xc42119c900, 0x0, 0x0)
	/Users/peterkaufman/go/src/github.com/acstech/doppler-events/vendor/github.com/couchbase/gocb/bucket_subdoc.go:155 +0x61a
github.com/acstech/doppler-events/vendor/github.com/couchbase/gocb.(*LookupInBuilder).execute(0xc421db35e0, 0x0, 0x0, 0x15de440, 0xc42119c900, 0xc421db35e0)
	/Users/peterkaufman/go/src/github.com/acstech/doppler-events/vendor/github.com/couchbase/gocb/bucket_subdoc.go:82 +0x47
github.com/acstech/doppler-events/vendor/github.com/couchbase/gocb.(*LookupInBuilder).Execute(0xc421db35e0, 0x0, 0x0, 0x0)
	/Users/peterkaufman/go/src/github.com/acstech/doppler-events/vendor/github.com/couchbase/gocb/bucket_subdoc.go:87 +0x33
github.com/acstech/doppler-events/internal/couchbase.(*Couchbase).collectEvents(0xc4228e5958, 0xc422ba9180, 0x7, 0x1535260, 0xc4203e9df0)
	/Users/peterkaufman/go/src/github.com/acstech/doppler-events/internal/couchbase/couchbaseConn.go:49 +0x206
github.com/acstech/doppler-events/internal/couchbase.(*Couchbase).ClientExists(0xc4228e5958, 0xc422ba9180, 0x7, 0x16aad60)
	/Users/peterkaufman/go/src/github.com/acstech/doppler-events/internal/couchbase/couchbaseConn.go:33 +0x43
github.com/acstech/doppler-events/internal/service.(*server).DisplayData(0xc4200af930, 0x16b1500, 0xc42208e6c0, 0xc421db20f0, 0xc4200af930, 0xc420d1fd70, 0x1570c60)
	/Users/peterkaufman/go/src/github.com/acstech/doppler-events/internal/service/service.go:95 +0xe4
github.com/acstech/doppler-events/rpc/eventAPI._EventAPI_DisplayData_Handler(0x15732e0, 0xc4200af930, 0x16b1500, 0xc42208e6c0, 0xc4200f4000, 0x0, 0x0, 0x0, 0x14e7826, 0x12)
	/Users/peterkaufman/go/src/github.com/acstech/doppler-events/rpc/eventAPI/eventAPI.pb.go:188 +0x241
github.com/acstech/doppler-events/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200fa1c0, 0x16b4b00, 0xc420842600, 0xc4201e2100, 0xc4201ba720, 0x19a83d0, 0x0, 0x0, 0x0)
	/Users/peterkaufman/go/src/github.com/acstech/doppler-events/vendor/google.golang.org/grpc/server.go:1011 +0x4fc
github.com/acstech/doppler-events/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200fa1c0, 0x16b4b00, 0xc420842600, 0xc4201e2100, 0x0)
	/Users/peterkaufman/go/src/github.com/acstech/doppler-events/vendor/google.golang.org/grpc/server.go:1249 +0x1318
github.com/acstech/doppler-events/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc422ba9170, 0xc4200fa1c0, 0x16b4b00, 0xc420842600, 0xc4201e2100)
	/Users/peterkaufman/go/src/github.com/acstech/doppler-events/vendor/google.golang.org/grpc/server.go:680 +0x9f
created by github.com/acstech/doppler-events/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/peterkaufman/go/src/github.com/acstech/doppler-events/vendor/google.golang.org/grpc/server.go:678 +0xa1
exit status 2`

**Comment by pjkaufman** [comment]
Error was caused by https://github.com/acstech/doppler-events/blob/master/internal/service/service.go#L94.
